services:
  - type: web
    name: glama-chat-interface
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GLAMA_API_KEY
        sync: false
    plan: free
